### ISSUE TITLE
Build Error: compilation error on MacOS X Yosemite with clang

### ISSUE THREAD

**Issue by DanCraft99** [jrosdahl/ccache#49]
In file included from conf.c:200:
confitems.gperf:33:35: error: static function 'parse_bool' is used in an inline function with external linkage [-Werror,-Wstatic-in-inline]
      {"stats",               23, ITEM(stats, bool)},
                                  ^
conf.c:196:2: note: expanded from macro 'ITEM'
        parse_##type, offsetof(struct conf, name), NULL
        ^
<scratch space>:72:1: note: expanded from here
parse_bool
^
confitems.gperf:54:1: note: use 'static' to give inline function 'confitems_get' internal linkage
__inline
^
static 
conf.c:39:1: note: 'parse_bool' declared here
parse_bool(const char *str, void *result, char **errmsg)

... 
and for all the static functions used to define the ITEM and ITEM_V macros

+ Clang
xcode 6.3.1 and 6.1.1
Apple LLVM version 6.1.0 (clang-602.0.49) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.1.0

+ Workaround
replace 
static bool parse_bool(const char str, void *result, char *errmsg)
{
}
with 
static inline bool parse_bool(const char str, void *result, char *errmsg)
{
}

or simply remove the static form the function.

**Comment by DanCraft99** [comment]
> remove the 'static' from the functions.

**Comment by DanCraft99** [comment]
Reopened. Accidentally close it.

**Comment by jrosdahl** [comment]
Already reported in https://bugzilla.samba.org/show_bug.cgi?id=11191, so closing this one.
