### ISSUE TITLE
ccache doesn't handle C++11 raw strings correctly

### ISSUE THREAD

**Issue by w-shackleton** [jrosdahl/ccache#50]
If I have a C++11 file containing a raw string such as:

```C++
const char* foo = R"(
    something
    http://google.com
)";
```

Then the // in the URL gets interpreted as a comment and any changes to the URL inside the raw string are counted as equivalent sources.

**Comment by jrosdahl** [comment]
Hi,

You forgot to mention which ccache version you are using.

It works for me with ccache 3.1.4, 3.1.11, 3.2.1, 3.2.2, latest 3.2-maint and latest master. Here's what I tried:

```
% CCACHE_LOGFILE=/dev/stdout ./ccache /usr/bin/g++ -std=c++11 -c github-issue-50.cc |& grep Result:
[2015-08-07T17:09:42.057664 6803 ] Result: cache miss                     
% CCACHE_LOGFILE=/dev/stdout ./ccache /usr/bin/g++ -std=c++11 -c github-issue-50.cc |& grep Result:
[2015-08-07T17:09:43.121590 6820 ] Result: cache hit (direct)             
% sed -i 's/com/comm/' github-issue-50.cc                                                          
% CCACHE_LOGFILE=/dev/stdout ./ccache /usr/bin/g++ -std=c++11 -c github-issue-50.cc |& grep Result:
[2015-08-07T17:09:48.431334 6838 ] Result: cache miss                     
% CCACHE_LOGFILE=/dev/stdout ./ccache /usr/bin/g++ -std=c++11 -c github-issue-50.cc |& grep Result:
[2015-08-07T17:11:06.386939 6966 ] Result: cache hit (direct)             
```

As can be seen above, there is a cache miss after adding an "m" after "com".

Could you supply more information on how to reproduce the problem?

**Comment by w-shackleton** [comment]
I'll try. I was using it in conjunction with other Build software. I was fairly convinced at the time that ccache was causing this issue but I'm not so sure now - I'll try to reproduce this issue in the environment I found the issue in. Thanks for posting those commands - I'll run those in my environment and see if I can get a repro. I'll reopen this issue if I find anything. 
Thanks!
