### ISSUE TITLE
Compression level being 1 regardless of configuration?

### ISSUE THREAD

**Issue by phonohawk** [jrosdahl/ccache#52]
This line looks quite suspicious to me:
https://github.com/jrosdahl/ccache/blob/25da80c2935646f22461d37fb1a768e742467ce3/ccache.c#L807

Shouldn't it be something like this?
```c
ret = copy_file(source, dest,
                conf->compression ? conf->compression_level : 0);
```

**Comment by jrosdahl** [comment]
Yes, thanks. Fixed in 1eef4547400f2ba0c49db4a47e0413612b81cc43.
