### ISSUE TITLE
Wrong hash table searched for file stats

### ISSUE THREAD

**Issue by ravron** [jrosdahl/ccache#65]
I believe [manifest.c:390][1] is searching the wrong hash table:

    struct file_stats *st = hashtable_search(hashed_files, path);

Shouldn't that line search `stated_files` if you want a `struct file_stats` out of the hash table?

[1]: https://github.com/jrosdahl/ccache/blob/master/manifest.c#L390

**Comment by jrosdahl** [comment]
That indeed seems to be the case. Fixed in 5459b15a. Thanks!
