### ISSUE TITLE
Seems to be missed man-file

### ISSUE THREAD

**Issue by dkrotx** [jrosdahl/ccache#67]
Hello!

Great idea to integrate ccache and memcached! I'll try this.
But seems to be there is missing manual page while installing.

revision - 18ce49909a1d5785514d3e7336ae2c397da3ca96

$ ./autogen.sh && ./configure && make && sudo make install
// skipped
/usr/bin/install -c -d /usr/local/bin
/usr/bin/install -c -m 755 ccache /usr/local/bin
/usr/bin/install -c -d /usr/local/share/man/man1
/usr/bin/install -c -m 644 ./ccache.1 /usr/local/share/man/man1/
/usr/bin/install: cannot stat ‘./ccache.1’: No such file or directory
make: [install] Error 1 (ignored)

**Comment by jrosdahl** [comment]
Thanks, fixed in b86784902d28defd5e475c8922de594787df4541.
